/*
================================================================================
                         FLIPKART SQL DATA ANALYTICS PROJECT
================================================================================

PROJECT TITLE:
    Flipkart E-Commerce Sales Analysis using MySQL

DATABASE:
    flipkart_db

TABLES:
    1. customers  -> customer master data
    2. products   -> product/catalog data
    3. sales      -> order-level transaction data

PROJECT OBJECTIVE:
    Analyze Flipkart customers, products and sales to understand:
    - sales and revenue performance
    - customer behavior
    - product/category/brand performance
    - state and city performance
    - payment preferences
    - order and delivery performance
    - discounts and coupons
    - customer segmentation
    - business trends

SQL CONCEPTS USED:
    SELECT, WHERE, ORDER BY, GROUP BY, HAVING, CASE, JOIN,
    SUBQUERIES, AGGREGATION, DISTINCT, LIMIT, DATE FUNCTIONS,
    NULL HANDLING, LEFT JOIN, INNER JOIN.

NOTE:
    The queries below are written for MySQL 8+.
    They return answers from your actual Flipkart database when executed.
================================================================================
*/


/*==============================================================================
  SECTION 0: DATABASE CHECK
==============================================================================*/

USE flipkart_db;

SHOW TABLES;

SELECT COUNT(*) AS total_customers FROM customers;
SELECT COUNT(*) AS total_products  FROM products;
SELECT COUNT(*) AS total_sales     FROM sales;


/*==============================================================================
  SECTION 1: PROJECT OVERVIEW
==============================================================================*/

/*
BUSINESS PROBLEM:

Flipkart has customer, product and sales transaction data. The objective is
to convert raw transactional data into useful business information.

The analysis answers questions such as:
    - How much revenue was generated?
    - Which states/categories/products perform strongly?
    - Which payment methods are preferred?
    - Which age groups contribute more sales?
    - How successful are deliveries?
    - Which customers and products are important?
    - How do sales change over time?
    - Which products have high discounts or low stock?
    - Which customers are repeat customers?

The final sections contain dashboard-based insights and a project conclusion.
*/

/* ============================================================
   FLIPKART SALES ANALYSIS
   52 IMPORTANT BUSINESS QUESTIONS + SQL ANSWERS
   Beginner-Friendly | Insight Focused
   ============================================================ */


/* ============================================================
   SECTION : BASIC BUSINESS OVERVIEW
   ============================================================ */


/* Q1. How many customers are present in the database? */

SELECT COUNT(*) AS Total_Customers
FROM customers;


/* Q2. How many products are available? */

SELECT COUNT(*) AS Total_Products
FROM products;


/* Q3. How many sales/order records are present? */

SELECT COUNT(*) AS Total_Sales_Records
FROM sales;


/* Q4. What is the total revenue generated? */

SELECT ROUND(SUM(Total_Amount), 2) AS Total_Revenue
FROM sales;


/* Q5. What is the total quantity of products sold? */

SELECT SUM(Quantity) AS Total_Quantity_Sold
FROM sales;


/* Q6. What is the average order value? */

SELECT ROUND(AVG(Total_Amount), 2) AS Average_Order_Value
FROM sales;


/* Q7. What is the highest order value? */

SELECT MAX(Total_Amount) AS Highest_Order_Value
FROM sales;


/* Q8. What is the lowest order value? */

SELECT MIN(Total_Amount) AS Lowest_Order_Value
FROM sales;


/* Q9. How many unique cities are represented in the sales data? */

SELECT COUNT(DISTINCT City) AS Unique_Cities
FROM sales;


/* Q10. How many unique states are represented in the sales data? */

SELECT COUNT(DISTINCT State) AS Unique_States
FROM sales;


/* ============================================================
   SECTION : SALES & ORDER ANALYSIS
   ============================================================ */


/* Q11. How many orders are there for each order status? */

SELECT
    Order_Status,
    COUNT(*) AS Total_Orders
FROM sales
GROUP BY Order_Status
ORDER BY Total_Orders DESC;


/* Q12. Which payment methods are used by customers? */

SELECT DISTINCT Payment_Mode
FROM sales
ORDER BY Payment_Mode;


/* Q13. Which are the highest-value orders above 50,000? */

SELECT
    Order_ID,
    Customer_ID,
    Total_Amount
FROM sales
WHERE Total_Amount > 50000
ORDER BY Total_Amount DESC;


/* Q14. What is the total revenue generated by each state? */

SELECT
    State,
    ROUND(SUM(Total_Amount), 2) AS Total_Revenue
FROM sales
GROUP BY State
ORDER BY Total_Revenue DESC;


/* Q15. What are the top 10 states by revenue? */

SELECT
    State,
    ROUND(SUM(Total_Amount), 2) AS Total_Revenue
FROM sales
GROUP BY State
ORDER BY Total_Revenue DESC
LIMIT 10;


/* Q16. What is the total revenue generated by each payment mode? */

SELECT
    Payment_Mode,
    ROUND(SUM(Total_Amount), 2) AS Total_Revenue
FROM sales
GROUP BY Payment_Mode
ORDER BY Total_Revenue DESC;


/* Q17. How many orders are placed through each payment mode? */

SELECT
    Payment_Mode,
    COUNT(*) AS Total_Orders
FROM sales
GROUP BY Payment_Mode
ORDER BY Total_Orders DESC;


/* Q18. What is the total revenue generated by each order status? */

SELECT
    Order_Status,
    ROUND(SUM(Total_Amount), 2) AS Total_Revenue
FROM sales
GROUP BY Order_Status
ORDER BY Total_Revenue DESC;


/* Q19. What is the monthly revenue trend? */

SELECT
    YEAR(Order_Date) AS Order_Year,
    MONTH(Order_Date) AS Order_Month,
    MONTHNAME(Order_Date) AS Month_Name,
    ROUND(SUM(Total_Amount), 2) AS Monthly_Revenue
FROM sales
GROUP BY
    YEAR(Order_Date),
    MONTH(Order_Date),
    MONTHNAME(Order_Date)
ORDER BY
    Order_Year,
    Order_Month;


/* Q20. What is the yearly revenue? */

SELECT
    YEAR(Order_Date) AS Order_Year,
    ROUND(SUM(Total_Amount), 2) AS Yearly_Revenue
FROM sales
GROUP BY YEAR(Order_Date)
ORDER BY Order_Year;


/* ============================================================
   SECTION 3: LOCATION & CUSTOMER ANALYSIS
   ============================================================ */


/* Q21. What is the quarterly revenue? */

SELECT
    YEAR(Order_Date) AS Order_Year,
    QUARTER(Order_Date) AS Quarter_Number,
    ROUND(SUM(Total_Amount), 2) AS Quarterly_Revenue
FROM sales
GROUP BY
    YEAR(Order_Date),
    QUARTER(Order_Date)
ORDER BY
    Order_Year,
    Quarter_Number;


/* Q22. What is the revenue generated by each city? */

SELECT
    City,
    ROUND(SUM(Total_Amount), 2) AS Total_Revenue
FROM sales
GROUP BY City
ORDER BY Total_Revenue DESC;


/* Q23. What are the top 10 cities by revenue? */

SELECT
    City,
    ROUND(SUM(Total_Amount), 2) AS Total_Revenue
FROM sales
GROUP BY City
ORDER BY Total_Revenue DESC
LIMIT 10;


/* Q24. What is the total revenue generated by each
        customer age group? */

SELECT
    Customer_Age_Group,
    ROUND(SUM(Total_Amount), 2) AS Total_Revenue,
    COUNT(*) AS Total_Orders
FROM sales
GROUP BY Customer_Age_Group
ORDER BY Total_Revenue DESC;


/* Q25. Which age group has the highest number of orders? */

SELECT
    Customer_Age_Group,
    COUNT(*) AS Total_Orders
FROM sales
GROUP BY Customer_Age_Group
ORDER BY Total_Orders DESC
LIMIT 1;


/* Q26. Which age group generates the highest revenue? */

SELECT
    Customer_Age_Group,
    ROUND(SUM(Total_Amount), 2) AS Total_Revenue
FROM sales
GROUP BY Customer_Age_Group
ORDER BY Total_Revenue DESC
LIMIT 1;


/* Q27. Which states have more than 100 unique customers? */

SELECT
    State,
    COUNT(DISTINCT Customer_ID) AS Unique_Customers
FROM sales
GROUP BY State
HAVING COUNT(DISTINCT Customer_ID) > 100
ORDER BY Unique_Customers DESC;


/* Q28. Which customers have placed more than 5 orders? */

SELECT
    Customer_ID,
    COUNT(*) AS Total_Orders
FROM sales
GROUP BY Customer_ID
HAVING COUNT(*) > 5
ORDER BY Total_Orders DESC;


/* Q29. Which customers are repeat customers? */

SELECT
    Customer_ID,
    COUNT(DISTINCT Order_ID) AS Total_Orders
FROM sales
GROUP BY Customer_ID
HAVING COUNT(DISTINCT Order_ID) > 1
ORDER BY Total_Orders DESC;


/* ============================================================
   SECTION : PRODUCT & CATEGORY ANALYSIS
   ============================================================ */


/* Q30. What is the average rating for each product category? */

SELECT
    Category,
    ROUND(AVG(Avg_Rating), 2) AS Average_Rating
FROM products
GROUP BY Category
ORDER BY Average_Rating DESC;


/* Q31. Which categories contain the largest number of products? */

SELECT
    Category,
    COUNT(*) AS Product_Count
FROM products
GROUP BY Category
ORDER BY Product_Count DESC;


/* Q32. Which brands have the largest number of products? */

SELECT
    Brand,
    COUNT(*) AS Product_Count
FROM products
GROUP BY Brand
ORDER BY Product_Count DESC;


/* Q33. What is the average selling price for each category? */

SELECT
    Category,
    ROUND(AVG(Selling_Price), 2) AS Average_Selling_Price
FROM products
GROUP BY Category
ORDER BY Average_Selling_Price DESC;


/* Q34. What is the revenue generated by each product category? */

SELECT
    p.Category,
    ROUND(SUM(s.Total_Amount), 2) AS Total_Revenue
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Total_Revenue DESC;


/* Q35. What is the revenue generated by each brand? */

SELECT
    p.Brand,
    ROUND(SUM(s.Total_Amount), 2) AS Total_Revenue
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Brand
ORDER BY Total_Revenue DESC;


/* Q36. Which products generated the highest revenue? */

SELECT
    p.Product_ID,
    p.Product_Name,
    p.Category,
    ROUND(SUM(s.Total_Amount), 2) AS Total_Revenue
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY
    p.Product_ID,
    p.Product_Name,
    p.Category
ORDER BY Total_Revenue DESC
LIMIT 10;


/* Q37. Which products have the highest sales quantity? */

SELECT
    p.Product_ID,
    p.Product_Name,
    SUM(s.Quantity) AS Total_Quantity_Sold
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY
    p.Product_ID,
    p.Product_Name
ORDER BY Total_Quantity_Sold DESC
LIMIT 10;


/* Q38. Which category sells the highest quantity? */

SELECT
    p.Category,
    SUM(s.Quantity) AS Total_Quantity_Sold
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Total_Quantity_Sold DESC
LIMIT 1;


/* ============================================================
   SECTION 5: DISCOUNT & PRICING ANALYSIS
   ============================================================ */


/* Q39. Which products have a discount of 20% or more? */

SELECT
    Product_ID,
    Product_Name,
    Discount_Percent,
    Original_Price,
    Selling_Price
FROM products
WHERE Discount_Percent >= 20
ORDER BY Discount_Percent DESC;


/* Q40. What is the average discount percentage by category? */

SELECT
    Category,
    ROUND(AVG(Discount_Percent), 2) AS Average_Discount_Percent
FROM products
GROUP BY Category
ORDER BY Average_Discount_Percent DESC;


/* Q41. What is the difference between original price
        and selling price? */

SELECT
    Product_ID,
    Product_Name,
    Original_Price,
    Selling_Price,
    ROUND(Original_Price - Selling_Price, 2) AS Price_Difference
FROM products
ORDER BY Price_Difference DESC;


/* Q42. Which products have the highest number of reviews? */

SELECT
    Product_ID,
    Product_Name,
    Total_Reviews,
    Avg_Rating
FROM products
ORDER BY Total_Reviews DESC
LIMIT 10;


/* Q43. How many products are there in each discount bucket? */

SELECT
    CASE
        WHEN Discount_Percent = 0 THEN 'No Discount'
        WHEN Discount_Percent BETWEEN 1 AND 10 THEN 'Low Discount'
        WHEN Discount_Percent BETWEEN 11 AND 20 THEN 'Medium Discount'
        ELSE 'High Discount'
    END AS Discount_Bucket,
    COUNT(*) AS Product_Count
FROM products
GROUP BY
    CASE
        WHEN Discount_Percent = 0 THEN 'No Discount'
        WHEN Discount_Percent BETWEEN 1 AND 10 THEN 'Low Discount'
        WHEN Discount_Percent BETWEEN 11 AND 20 THEN 'Medium Discount'
        ELSE 'High Discount'
    END
ORDER BY Product_Count DESC;


/* ============================================================
   SECTION 6: CUSTOMER & PAYMENT INSIGHTS
   ============================================================ */


/* Q44. What is the revenue generated by each customer tier? */

SELECT
    c.Customer_Tier,
    ROUND(SUM(s.Total_Amount), 2) AS Total_Revenue,
    COUNT(DISTINCT c.Customer_ID) AS Unique_Customers
FROM sales s
INNER JOIN customers c
    ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_Tier
ORDER BY Total_Revenue DESC;


/* Q45. Which customers generated the highest revenue? */

SELECT
    c.Customer_ID,
    c.Customer_Name,
    ROUND(SUM(s.Total_Amount), 2) AS Customer_Revenue
FROM customers c
INNER JOIN sales s
    ON c.Customer_ID = s.Customer_ID
GROUP BY
    c.Customer_ID,
    c.Customer_Name
ORDER BY Customer_Revenue DESC
LIMIT 10;


/* Q46. What is the average order value for each payment mode? */

SELECT
    Payment_Mode,
    ROUND(AVG(Total_Amount), 2) AS Average_Order_Value
FROM sales
GROUP BY Payment_Mode
ORDER BY Average_Order_Value DESC;


/* Q47. Which payment mode is most preferred by order count? */

SELECT
    Payment_Mode,
    COUNT(*) AS Total_Orders
FROM sales
GROUP BY Payment_Mode
ORDER BY Total_Orders DESC
LIMIT 1;


/* ============================================================
   SECTION 7: DELIVERY & BUSINESS PERFORMANCE
   ============================================================ */


/* Q48. What percentage of orders were successfully delivered? */

SELECT
    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Order_Status = 'Delivered' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Delivery_Success_Percentage
FROM sales;


/* Q49. What is the average delivery time in days? */

SELECT
    ROUND(
        AVG(DATEDIFF(Delivery_Date, Order_Date)),
        2
    ) AS Average_Delivery_Days
FROM sales
WHERE Delivery_Date IS NOT NULL
  AND Order_Date IS NOT NULL;


/* Q50. Which states have the highest average delivery time? */

SELECT
    State,
    ROUND(
        AVG(DATEDIFF(Delivery_Date, Order_Date)),
        2
    ) AS Average_Delivery_Days
FROM sales
WHERE Delivery_Date IS NOT NULL
  AND Order_Date IS NOT NULL
GROUP BY State
ORDER BY Average_Delivery_Days DESC;

/*==============================================================================
  SECTION: PRODUCT INFORMATION QUESTIONS
==============================================================================*/


/*
Q51. Which sales orders have an order value greater than the
    average order value of all sales?

*/

SELECT
    Order_ID,
    Customer_ID,
    Total_Amount
FROM sales
WHERE Total_Amount > (
    SELECT AVG(Total_Amount)
    FROM sales
)
ORDER BY Total_Amount DESC;


/*
Q52. Which products have an average rating higher than the
    overall average product rating?

*/

SELECT
    Product_ID,
    Product_Name,
    Avg_Rating
FROM products
WHERE Avg_Rating > (
    SELECT AVG(Avg_Rating)
    FROM products
)
ORDER BY Avg_Rating DESC;


/*==============================================================================
  SECTION : FINAL BUSINESS INSIGHTS
==============================================================================*/

/*
1. SALES GROWTH:
   The dashboard presents an overall positive sales trend, with multiple
   high-performing months. The monthly trend query identifies the exact
   months responsible for the strongest revenue contribution.

2. GEOGRAPHICAL PERFORMANCE:
   Uttar Pradesh, Rajasthan and Haryana are highlighted by the dashboard as
   major sales-contributing states. State-level revenue and revenue-share
   queries can verify their exact contribution.

3. CUSTOMER AGE:
   The 26–35 age group is highlighted as the leading contributor to sales,
   followed by 18–25 and 36–45. This makes younger customer segments an
   important part of the transaction mix shown in the dashboard.

4. PAYMENT PREFERENCE:
   UPI is highlighted as the preferred payment method, followed by COD,
   Debit Card and Credit Card. Payment-mode queries measure both usage and
   monetary contribution.

5. DELIVERY:
   The dashboard indicates a high proportion of successfully delivered
   orders. Delivery success percentage and average delivery time provide
   measurable operational KPIs.

6. CUSTOMER ENGAGEMENT:
   The dashboard emphasizes a strong customer base and repeat-order
   activity. Repeat-customer analysis separates one-time customers from
   customers who place multiple orders.

7. PRODUCT PERFORMANCE:
   Product-level revenue, quantity sold, rating and review counts can be
   combined to identify products contributing strongly to business results.

8. DISCOUNT ANALYSIS:
   Discount buckets separate products into no-discount, low, medium and
   high-discount groups. This supports analysis of discount patterns against
   product ratings and sales.

9. OPERATIONAL PERFORMANCE:
   Shipping cost and delivery-time analysis by state can reveal geographic
   differences in fulfillment performance.

10. CUSTOMER VALUE:
    Customer-level revenue and customer-tier analysis identify customers
    contributing the greatest monetary value.


/*==============================================================================
  SECTION : PROJECT CONCLUSION
==============================================================================*/

/*
CONCLUSION:

This Flipkart SQL project demonstrates how raw e-commerce transaction data
can be transformed into business information using MySQL.

The project moves from basic data exploration to advanced analytics.
SELECT, WHERE and ORDER BY are used for inspection and filtering.
GROUP BY, aggregation and HAVING summarize business performance.
CASE creates useful business segments.
JOINs connect customers, products and sales.
Subqueries compare records against overall and group-level averages.

The supplied dashboard highlights these major themes:
    - positive sales growth
    - strong contribution from major states
    - strong contribution from younger customer groups
    - UPI as the highlighted payment preference
    - high delivery success
    - strong customer base and repeat engagement

The SQL analysis also provides a framework for deeper analysis of:
    - product performance
    - discounts and coupons
    - customer value
    - payment behavior
    - geographic performance
    - delivery operations
    - monthly and customer-level rankings

Overall, this project shows how SQL can convert Flipkart transactional data
into structured business analysis and can serve as the SQL backend analysis
for an Excel/dashboard-based data analytics project.

END OF FLIPKART SQL PROJECT
================================================================================
*/
